# Generated by Django 4.2.16 on 2026-02-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TechnologyModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "tech_type",
                    models.CharField(
                        choices=[
                            ("xai", "Explainable AI"),
                            ("iot", "IoT Integration"),
                            ("edge", "Edge Computing"),
                            ("hrc", "Human-Robot Collaboration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("benefits", models.TextField()),
                ("use_cases", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "technology_modules",
            },
        ),
    ]
