# Generated by Django 4.2.16 on 2026-02-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictiveMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.CharField(max_length=50)),
                ("temperature", models.FloatField()),
                ("vibration", models.FloatField()),
                ("pressure", models.FloatField()),
                ("runtime_hours", models.FloatField()),
                ("failure_predicted", models.BooleanField(default=False)),
                ("prediction_score", models.FloatField(default=0.0)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "predictive_maintenance",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessOptimization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process_name", models.CharField(max_length=100)),
                ("efficiency_before", models.FloatField()),
                ("efficiency_after", models.FloatField()),
                ("improvement_percent", models.FloatField()),
                ("ai_recommendation", models.TextField()),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "process_optimization",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=50)),
                ("defect_type", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="quality_images/"
                    ),
                ),
                ("ai_confidence", models.FloatField(default=0.0)),
                ("ai_detected", models.BooleanField(default=False)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "quality_control",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplyChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_name", models.CharField(max_length=150)),
                ("component", models.CharField(max_length=100)),
                ("delivery_days", models.IntegerField()),
                ("price_volatility", models.FloatField(default=0.5)),
                ("past_delays", models.IntegerField(default=0)),
                ("distance_km", models.IntegerField(default=500)),
                ("defect_rate", models.FloatField(default=0.02)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ai_insight", models.TextField()),
                ("ai_predicted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "supply_chain",
                "ordering": ["-created_at"],
            },
        ),
    ]
